name: Exported Components Security Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Run the security check
      - name: Run security check
        run: |
            finding=$(python check_exported.py ./InsecureBankv2/app/src/main/AndroidManifest.xml)
            
            if [[ -z $finding ]]; then 
              echo "No issues found"; 
            else 
              echo "::set-output name=script_output::$finding" 
              echo $finding
              fi
      
          
          

      # Step 4: Upload SARIF file to GitHub Security tab
      - name: Upload SARIF to GitHub Security
        if: steps.run_check.outputs.script_output != ''
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: findings.sarif
