name: SSH Connection Example

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  ssh-connect:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
       

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect to Server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@34.229.151.203 -i id_rsa 'echo "Hello from GitHub Actions!"'
